controller_costmap:
    global_frame: odom
    robot_base_frame: base_footprint
    update_frequency: 5.0
    publish_frequency: 10

    width: 20
    height: 20
    resolution: 0.05
    footprint: [[1.7, 0.85], [1.169, 0.85], [1.169, 0.567], [-0.54, 0.567], [-0.54, -0.567], [1.169, -0.567], [1.169, -0.85], [1.7, -0.85]]
    # robot_radius: 0.55
    footprint_padding: 0.0
    transform_tolerance: 0.5
    rolling_window: true
    always_send_full_costmap: true

    plugins:
      - {name: static_layer,            type: "navit_costmap::StaticLayer"}
      - {name: obstacle_layer,          type: "navit_costmap::ObstacleLayer"}
      - {name: inflation_layer,         type: "navit_costmap::InflationLayer"}

    obstacle_layer:
        observation_sources: lidar_1
        lidar_1:
            topic: base_scan 
            sensor_frame: base_laser_link
            data_type: LaserScan
            marking: true
            clearing: true
            inf_is_valid: true
            obstacle_range: 10
            raytrace_range: 15 # 清除障碍物范围
            min_obstacle_height: 0.0
            max_obstacle_height: 2.0
            observation_persistence: 3.0 # 障碍物停留时间
            # expected_update_rate: 0.0 # 更新间隔 [s]，设置为 0.0 表示允许传感器长时间不更新
            track_unknown_space: false # 栅格 3 个状态 [自由][障碍物][未知]，这里配置是否有[未知]状态
            combination_method: 1 # 传感器数据更新到地图的方式，[enum] @0：覆盖；@1：最大值；@99：无操作
            footprint_clearing_enabled: false # 清空机器 fp 内容


    inflation_layer:
        inflation_radius: 2.0
        cost_scaling_factor: 0.43


