base_frame_id: "base_link"
odom_frame_id: "odom"
cmd_vel_in_topic: "/controller_cmd_vel"
cmd_vel_out_topic: "/collision_monitor_cmd_vel"
state_topic: "collision_monitor_state"
transform_tolerance: 0.5
source_timeout: 5.0
base_shift_correction: True
stop_pub_timeout: 2.0
min_linear_vel: 0.21
min_angular_vel: 0.0
# Polygons represent zone around the robot for "stop" and "slowdown" action types,
# and robot footprint for "approach" action type.
# Footprint could be "polygon" type with dynamically set footprint from footprint_topic
# or "circle" type with static footprint set by radius. "footprint_topic" parameter
# to be ignored in circular case.
polygons: ["PolygonSlow"]
PolygonStop:
  # type可选： "polygon" "circle"
  type: "polygon"
  # (TODO):footprint 读取方式可以改进
  # points: [[1.169, 0.85], [1.169, 0.85], [1.169, 0.65], [-0.60, 0.70], [-0.60, -0.65], [1.169, -0.65], [1.169, -0.85], [1.169, -0.85]]
  points: [1.169, 0.65, -0.60, 0.65, -0.60, -0.65, 1.169, -0.65]
  action_type: "stop"
  min_points: 4
  visualize: True
  polygon_pub_topic: "polygon_stop"
PolygonSlow:
  type: "polygon"
  # (TODO):footprint 读取方式可以改进
  # 横向 0.5m
  points: [4.5, 1.5, -0.60, 1.5, -0.60, -1.5, 4.5, -1.5]
  action_type: "slowdown"
  min_points: 4
  slowdown_ratio: 1.0
  visualize: True
  polygon_pub_topic: "polygon_slowdown"
FootprintApproach:
  type: "polygon"
  action_type: "approach"
  footprint_topic: "/navit_controller_node/controller_costmap/footprint"
  time_before_collision: 2.0
  simulation_time_step: 0.1
  min_points: 6
  visualize: False
observation_sources: [ "lidar_front", "lidar_back", "sim_laser_scan" ]
lidar_front:
  type: "scan"
  topic: "/scan_front"
  sensor_frame: "base_link"

lidar_back:
  type: "scan"
  topic: "/scan_back"
  sensor_frame: "base_link"

sim_laser_scan:
  type: "scan"
  topic: "/base_scan"
  sensor_frame: "base_laser_link"
