approach_dock:
    odom_topic_name: /odom
    cmd_vel_name: /cmd_vel
    control_frequency: 5.0
    obstacle_blocking_timeout: 20.0
    collision_check_forward_distance: 0.5
    collision_check_forward_time: 0.8
    lost_perception_timeout: 150.0
    pre_in_percep_x: -2.55 # 车头对桩 3.0 # 车尾对桩 -2.55
    pre_in_percep_y: 0.0
    pre_in_percep_theta: 3.141593 # 车头对桩 0.0 # 车尾对桩 3.141593
    wheel_base: -1 # 后轮中心到前轮的轴距，-1 表示里程计的 angular.z 为角速度 # 0.95

    ## load available controller plugins
    ## or the same controller with different params
    ## the action goal msg requires controller_plugin_name
    ## NMPC：dock_fg100_controller/FgController
    controller:
        # - name: GracefulController
        #   type: dock_diff_graceful_controller/Controller

        - name: FgController
          type: dock_fg100_controller/FgController

        - name: DiffPurepursuitController
          type: dock_diff_purepursuit_pid_controller/Controller
## load all useful  perception plugins, same or different
## the action goal requres perception_plugin_name
    perception:
      - name: fake_perception
        type: dock_fake_perception/FakePerception

      - name: 2d_lidar
        type: dock_perception/Perception

      - name: visual_perception
        type: dock_visual_perception/VisualPerception

    filter:
      - name: ekf_1
        type: PerceptionEKF

      - name: average
        type: AverageFilter

      - name: lkf
        type: PerceptionLKF

ekf_1:
    sigma_w: [1.0e-3, 1.0e-3, 1.0e-3]
    sigma_u: [1.0e-2, 1.0e-2, 1.0e-2]
    error_cov: [10, 10, 10]
    dt: 0.01

GracefulController:
    k1: 1.0
    k2: 2.0
    min_velocity: 0.02
    max_velocity: 0.2
    max_angular_velocity: 0.2
    min_angular_velocity: 0.1
    beta: 0.3
    lambda: 2.0
    xy_tolerance: 0.03
    yaw_tolerance: 0.03
    base_frame: base_link

DiffPurepursuitController:
    half_length_robot: 0.8
    ld_: 1.0
    k_control_: 2.0
    min_velocity: 0.03
    max_velocity: 0.2
    max_angular_velocity: 0.6
    min_angular_velocity: 0.1
    beta: 0.3
    lambda: 2.0
    xy_tolerance: 0.07
    yaw_tolerance: 0.1
    base_frame: base_link

FgController:
    xy_goal_tolerance: 0.02 # 0.03
    yaw_goal_tolerance: 0.054 # 0.02
    robot:
        type: "simple_car"
        simple_car:
            wheelbase: 0.95 # 1.0
            max_vel_x: 0.23 # 0.2
            max_vel_x_backwards: 0.2
            max_steering_angle: 0.6 # 原本是 1.2 的转角，这里增大机器的转弯半径把角度改小 # 0.6
            acc_lim_x: 0.1 # deactive bounds with zero
            dec_lim_x: 0.1 # deactive bounds with zero
            max_steering_rate: 0.07 # deactive bounds with zero # 0.1

    grid:
        grid_size_ref: 60 # (T = (grid_size_ref-1) * dt_ref); # 50
        dt_ref: 0.3 # and here the corresponding temporal resolution # 0.5
        xf_fixed: [True, True, True]
        warm_start: True
        collocation_method: "forward_differences"
        cost_integration_method: "left_sum"

    planning:
        objective:
          type: "quadratic_form"
          quadratic_form:
            state_weights: [5.0, 5.0, 2.0] # [2.0, 2.0, 2]
            control_weights: [0.1, 0.1] # [0.1, 0.05]
            integral_form: False
        terminal_cost:
          type: "none" # can be "none" # none # quadratic
          quadratic:
            final_state_weights: [10.0, 10.0, 10.0] # [1.0, 15.0, 10.0]
        terminal_constraint:
          type: "none" # can be "none"
          l2_ball:
            weight_matrix: [1.0, 1.0, 1.0]
            radius: 5

    controller:
        state_feedback_topic_name: move_base_node/mpc_local_planner/state_feedback #TODO 替换为实际的topic名字
        outer_ocp_iterations: 1
        xy_goal_tolerance: 0.02 # 0.2
        yaw_goal_tolerance: 0.054 # 0.1
        prefer_x_feedback: False
        publish_ocp_results: False

    solver:
      ipopt:
        iterations: 20 # 100
        max_cpu_time: -1.0
        ipopt_numeric_options:
          tol: 1e-4 # tolerance
        ipopt_string_options:
          linear_solver: "mumps"
          hessian_approximation: "limited-memory"


fake_perception:
    tracking_frame: map

2d_lidar:
    tracking_frame: odom
    use_filter: true
    debug: true
    max_alignment_error: 0.01
    scan_topic_name: /livox/lidar_192_168_1_168
    use_scandata: false # true for stage sim
    max_icp_iterations: 12 # 10

    dock_shape: v_shape
    mir_shape:
       v_shape_l: 0.15
       v_shape_theta_deg: 120.0
       bottom_l: 0.3
    v_shape:
       l: 0.15
       theta_deg: 140.0
      #  theta_deg: 135.0 #  Perception plugin getPose failed
    reflective_stripe_range_x_min: 0.1
    reflective_stripe_range_x_max: 10.0
    reflective_stripe_range_y_min: -5.0
    reflective_stripe_range_y_max: 5.0
    reflective_stripe_range_z_min: 0.1
    reflective_stripe_range_z_max: 3.0
    reflective_stripe_intensity_threshold: 180
    frame_number_of_reflective_stripe_cloud: 10
    offset_translation_x: -0.0068276614618647535
    offset_translation_y: -0.048487970028640984
    offset_rotation_x: 0.0
    offset_rotation_y: 0.0
    offset_rotation_z: -0.017892324515351467
    offset_rotation_w: 0.9998399195488432
    pose_tolerance: 0.4

visual_perception:
    marker_size: 9.0
    max_new_marker_error: 0.08
    max_track_error: 0.2
    max_frequency: 20
    marker_resolution: 5
    marker_margin: 2
    input_id: 1
    cam_info_topic: "/camera_01/rgb/camera_info"
    cam_image_topic: "/camera_01/rgb/image_raw"
    roll: 1.57
    pitch: 1.57
    yaw: 0.0

lkf:
  x_estimate_noise: 0.15
  x_measure_noise: 0.04
  x_project_noise: 0.006
  y_estimate_noise: 0.1
  y_measure_noise: 0.023 # 0.03
  y_project_noise: 0.002 # 0.07
  yaw_estimate_noise: 0.3
  yaw_measure_noise: 0.1
  yaw_project_noise: 0.005
