global_costmap:
    global_frame: map
    robot_base_frame: base_link
    robot_radius: 0.5
    update_frequency: 0.5
    publish_frequency: 0.5

    width: 100
    height: 100
    resolution: 0.025
     
    transform_tolerance: 0.5
    #rolling_window: true
    plugins:
      - {name: static_layer,            type: "navit_costmap::StaticLayer"}
      # - {name: obstacle_layer,          type: "navit_costmap::VoxelLayer"}
      # - {name: prohibition_layer,        type: "costmap_prohibition_layer_namespace::CostmapProhibitionLayer"}
      - {name: inflation_layer,         type: "navit_costmap::InflationLayer"}
    

    # obstacle_layer:
    #     observation_sources: lidar
    #     lidar:
    #         topic: hokuyo_lida/scan
    #         sensor_frame: laser_link
    #         data_type: LaserScan
    #         marking: true
    #         clearing: true
    #         obstacle_range: 8
    #         raytrace_range: 10

    inflation_layer:
        inflation_radius: 5.0
        cost_scaling_factor: 1.0

    prohibition_layer:
      prohibition_areas:
        # point
        - [18,12]

        # line
        - [[8,2], [8,22]]
        
        # polygons 
        - [[1, 3],
           [1, 1],
           [3, 1],
           [3, 3]]
        - [[5, 7],
          [5, 5],
          [7, 5],
          [7, 7]]




