local_costmap:
    global_frame: odom
    robot_base_frame: base_footprint
    update_frequency: 5.0
    publish_frequency: 10

    width: 50
    height: 50
    resolution: 0.05

    transform_tolerance: 0.5
    rolling_window: true
    always_send_full_costmap: true

    plugins:
      - {name: static_layer,            type: "navit_costmap::StaticLayer"}
      - {name: obstacle_layer,          type: "navit_costmap::ObstacleLayer"}
      - {name: inflation_layer,         type: "navit_costmap::InflationLayer"}

    obstacle_layer:
        observation_sources: lidar_1 lidar_2
        lidar_1:
            topic: base_scan 
            sensor_frame: laser_link
            data_type: LaserScan
            marking: true
            clearing: true
            obstacle_range: 8
        lidar_2:
            topic: scan_filtered_2
            sensor_frame: laser_link
            data_type: LaserScan
            marking: true
            clearing: true
            obstacle_range: 8
    inflation_layer:
        inflation_radius: 0.4
        cost_scaling_factor: 1.5


