test_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5
  publish_frequency: 5
  track_unknown_space: true
  width: 10
  height: 10
  resolution: 0.05

  plugins:
    - {name: static_layer,            type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}

  inflation_layer:
    enabled:              true
    cost_scaling_factor:  1.2  # exponential rate at which the obstacle cost drops off (default: 10)
    inflation_radius:     1.3  # max. distance from an obstacle at which costs are incurred for planning paths.

  static_layer:
    enabled:              true
    map_topic:            "/map"
