Header header

string message_id

uint32 gps_week

# UTC seconds from midnight
float64 utc_seconds

float64 heading
float64 pitch
float64 roll

float64 gyro_x
float64 gyro_y
float64 gyro_z

float64 acc_x
float64 acc_y
float64 acc_z

float64 lattitude
float64 longitude
float64 altitude

float64 vel_e
float64 vel_n
float64 vel_u
float64 vel_vehicle

uint32 navsatelites_1
uint32 navsatelites_2

uint8 status

uint32 diff_age

uint8 warning