controller_costmap:
    global_frame: odom
    robot_base_frame: base_link
    robot_radius: 0.4
    update_frequency: 10.0
    publish_frequency: 2.5

    width: 6
    height: 6
    resolution: 0.05
     
    transform_tolerance: 0.5
    rolling_window: true
    always_send_full_costmap: true

    plugins:
      - {name: static_layer,    type: "navit_costmap::StaticLayer" }
      - {name: obstacle_layer,  type: "navit_costmap::ObstacleLayer"}
      - {name: inflation_layer, type: "navit_costmap::InflationLayer"}

    obstacle_layer:
        observation_sources: lidar_1 
        lidar_1:
            topic: /base_scan
            sensor_frame: laser_link
            data_type: LaserScan
            marking: true
            clearing: true
            obstacle_range: 8

    inflation_layer:
        inflation_radius: 0.1
        cost_scaling_factor: 0.5


