local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint
  update_frequency: 10.0
  publish_frequency: 10.0
  static_map: false
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.05
  transform_tolerance: 1.0

  inscribed_radius: 0.2
  circumscribed_radius: 0.35
  clearing_radius: 0.2


  plugins:
    # - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
    
  static_layer:
      map_topic: /navit_planner_node/planner_costmap/costmap

  obstacle_layer:
      observation_sources: scan
      scan:
          topic: /base_scan
          sensor_frame: base_laser_link
          data_type: LaserScan
          marking: true
          clearing: true
          obstacle_range: 8
          raytrace_range: 20
  
  inflation_layer:
      inflation_radius: 1.0
      cost_scaling_factor: 0.8
