controller_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 10.0
  publish_frequency: 2.5
  # no brush
  # footprint: '[[1.3, 0.567], [1.3, -0.567], [-0.54, -0.567], [-0.54, 0.567]]'

  # brush closed
  # footprint: '[ [1.7, 0.567], [1.7, -0.567], [-0.54, -0.567], [-0.54, 0.567]] '

  # brush open
  footprint: [[1.25, 0.65], [-0.65, 0.65], [-0.65, -0.65], [1.25, -0.65]]
  footprint_padding: 0.0
  width: 20
  height: 20
  resolution: 0.1

  transform_tolerance: 0.5
  rolling_window: true
  always_send_full_costmap: false

  plugins:
    # - { name: static_layer,            type: "navit_costmap::StaticLayer" }
    - { name: obstacle_layer,          type: "navit_costmap::ObstacleLayer"}
    # - { name: obstacle_layer_3d,       type: "navit_costmap::VoxelLayer" }
    - { name: inflation_layer,         type: "navit_costmap::InflationLayer"}

  obstacle_layer:
        observation_sources: lidar_front lidar_back sim_laser_scan vanjee_laser_scan
        enabled: true
        lidar_front:
            topic: scan_front
            sensor_frame: base_link
            data_type: LaserScan
            marking: true
            clearing: true
            obstacle_range: 10 # 设置障碍物范围
            raytrace_range: 6 # 清除障碍物范围
            # raytrace_max_range: 5.0
            # raytrace_min_range: 0.0
            observation_persistence: 1.0 # 观测数据的保留时间
            # expected_update_rate: 0.0 # 更新间隔 [s]，设置为 0.0 表示允许传感器长时间不更新
            track_unknown_space: false # 栅格 3 个状态 [自由][障碍物][未知]，这里配置是否有[未知]状态
            combination_method: 1 # 传感器数据更新到地图的方式，[enum] @0：覆盖；@1：最大值；@99：无操作
            footprint_clearing_enabled: true # 清空机器 fp 内容
            inf_is_valid: true
        lidar_back:
            topic: scan_back
            sensor_frame: base_link
            data_type: LaserScan
            marking: true
            clearing: true
            obstacle_range: 10 # 设置障碍物范围
            raytrace_range: 6 # 清除障碍物范围
            observation_persistence: 1.0 # 观测数据的保留时间
            # expected_update_rate: 0.0 # 更新间隔 [s]，设置为 0.0 表示允许传感器长时间不更新
            track_unknown_space: false # 栅格 3 个状态 [自由][障碍物][未知]，这里配置是否有[未知]状态
            combination_method: 1 # 传感器数据更新到地图的方式，[enum] @0：覆盖；@1：最大值；@99：无操作
            footprint_clearing_enabled: true # 清空机器 fp 内容
            inf_is_valid: true
        sim_laser_scan:
            topic: /base_scan
            sensor_frame: base_laser_link
            data_type: LaserScan
            marking: true
            clearing: true
            obstacle_range: 10 # 设置障碍物范围
            raytrace_range: 15 # 清除障碍物范围
            # observation_persistence: 3.0 # 观测数据的保留时间
            # expected_update_rate: 0.0 # 更新间隔 [s]，设置为 0.0 表示允许传感器长时间不更新
            track_unknown_space: false # 栅格 3 个状态 [自由][障碍物][未知]，这里配置是否有[未知]状态
            combination_method: 1 # 传感器数据更新到地图的方式，[enum] @0：覆盖；@1：最大值；@99：无操作
            footprint_clearing_enabled: true # 清空机器 fp 内容
            inf_is_valid: true

        front_laser_scan:
            topic: /laser_scan_front
            sensor_frame: laser_front_link
            data_type: LaserScan
            marking: true
            clearing: true
            obstacle_range: 10 # 设置障碍物范围
            raytrace_range: 15 # 清除障碍物范围
            # observation_persistence: 3.0 # 观测数据的保留时间
            # expected_update_rate: 0.0 # 更新间隔 [s]，设置为 0.0 表示允许传感器长时间不更新
            track_unknown_space: false # 栅格 3 个状态 [自由][障碍物][未知]，这里配置是否有[未知]状态
            combination_method: 1 # 传感器数据更新到地图的方式，[enum] @0：覆盖；@1：最大值；@99：无操作
            footprint_clearing_enabled: true # 清空机器 fp 内容
            inf_is_valid: true
            use_radiu_filter: true
            radiu_threshold: 0.1
            min_neighbors: 2

        back_laser_scan:
            topic: /laser_scan_back
            sensor_frame: laser_back_link
            data_type: LaserScan
            marking: true
            clearing: true
            obstacle_range: 10 # 设置障碍物范围
            raytrace_range: 15 # 清除障碍物范围
            # observation_persistence: 3.0 # 观测数据的保留时间
            # expected_update_rate: 0.0 # 更新间隔 [s]，设置为 0.0 表示允许传感器长时间不更新
            track_unknown_space: false # 栅格 3 个状态 [自由][障碍物][未知]，这里配置是否有[未知]状态
            combination_method: 1 # 传感器数据更新到地图的方式，[enum] @0：覆盖；@1：最大值；@99：无操作
            footprint_clearing_enabled: true # 清空机器 fp 内容
            inf_is_valid: true
            use_radiu_filter: true
            radiu_threshold: 0.1
            min_neighbors: 2

        vanjee_laser_scan:
            topic: /scan_middle
            sensor_frame: base_link
            data_type: LaserScan
            marking: true
            clearing: true
            obstacle_range: 10 # 设置障碍物范围
            raytrace_range: 15 # 清除障碍物范围
            # observation_persistence: 3.0 # 观测数据的保留时间
            # expected_update_rate: 0.0 # 更新间隔 [s]，设置为 0.0 表示允许传感器长时间不更新
            track_unknown_space: false # 栅格 3 个状态 [自由][障碍物][未知]，这里配置是否有[未知]状态
            combination_method: 1 # 传感器数据更新到地图的方式，[enum] @0：覆盖；@1：最大值；@99：无操作
            footprint_clearing_enabled: true # 清空机器 fp 内容
            inf_is_valid: true

  inflation_layer:
    # exp(-1.0 * cost_scaling_factor * (distance_from_obstacle - inscribed_radius)) * (costmap_2d::INSCRIBED_INFLATED_OBSTACLE - 1)
    # exp(-1.0 * cost_scaling_factor * (车头1.5 - 内切0.5)) * 253 = 最小碰撞值128
    # cost_scaling_factor = ln(128/253)*-1.0/(车头1.5 - 内切0.5) = 0.681359
    inflation_radius: 2.0
    cost_scaling_factor: 0.681359
