uint16 CMD_CLEAR = 0
uint16 CMD_START_RECORD_POLYGON =1
uint16 CMD_START_RECORD_PATH = 2
uint16 CMD_START_RECORD_POINT = 3
uint16 CMD_FINISH_RECORD = 5

uint16 mode             # 0 is mapping 1 is localization
uint16 cmd              # one of the above commands
string frame_id         # optional, defaults to "map"

---
bool success
geometry_msgs/PoseStamped[] poses_stamped
