# Example configuration:
# - velocity limits are around a 10% above the physical limits
# - acceleration limits are just low enough to avoid jerking

twist: 
    # mandatory parameters
    speed_lim_vx: 0.8
    speed_lim_vy: 0.8
    speed_lim_w: 5.4
    
    accel_lim_vx: 0.3
    accel_lim_vy: 0.3
    accel_lim_w: 3.5
    
    # optional parameters
    frequency: 5.0
    decel_factor: 1.0
    decel_factor_safety: 1.0
    
    # robot velocity feedback type:
    #  0 - none
    #  1 - odometry
    #  2 - end robot commands
    robot_feedback: 2
   
    topic_names:
        odometry: odom
        robot_cmd_vel: none
        raw_cmd_vel: cmd_vel_raw
        smooth_cmd_vel: cmd_vel
