nav_planner:
     - name: test_1
       type: global_planner/GlobalPlanner
    
     - name: test_2
       type: navfn/NavfnROS

     - name: test_3
       type: smac_planner/SmacPlanner2D
coverage_planner:
     - name: test_1
       type: complete_coverage_planner/CompleteCoveragePlanner

     - name: test_2
       type: complete_coverage_planner/CompleteCoveragePlanner

     - name: test_3
       type: complete_coverage_planner/CompleteCoveragePlanner
    #- name: test_1
    #  type: smac_planner/SmacPlanner2D
test_1:
  map_resolution: 0.05              # [m], default = 0.05
  coverage_resolution: 0.1          # [m], default = 0.1
  robot_radius: 0.25                 # [m], default = 0.2
  coverage_interval_distance: 1.0   # [m], coverage interval dis is robot_radius * 2 * 2
  error_distance: 3                 # [pixel], error distance for turn circle ccpp
  path_eps: 1.0                     # [pixel],for downsample path,the distance between points when generating a path
  inflation_distance: 0.2
    #test_1:
    #    smooth_path: false
    #    downsample_costmap: true
    #    downsampling_factor: 4
    #    max_iterations: 15000
    #
    #test_2:
    #    smooth_path: false
    #    downsample_costmap: true
    #    downsampling_factor: 4
    #    max_iterations: 18000
    #
    #test_3:
    #    smooth_path: false
    #    downsample_costmap: true
    #    downsampling_factor: 4
    #    max_iterations: 15000
