coverage_planner:
     - name: ccpp
       type: complete_coverage_planner/CompleteCoveragePlanner

nav_planner:
     #- {name: topoint, type: global_planner/GlobalPlanner}
     - {name: topoint, type: navfn/NavfnROS}

smooth_path_planner:
     - {name: gsl_smooth, type: path_smoother/PathGslSpline}

ccpp:
  map_resolution: 0.05              # [m], default = 0.05
  coverage_resolution: 0.1          # [m], default = 0.1
  robot_radius: 0.1                 # [m], default = 0.2
  coverage_interval_distance: 0.4   # [m], coverage interval dis is robot_radius * 2 * 2
  error_distance: 3                 # [pixel], error distance for turn circle ccpp
  path_eps: 1.0                     # [pixel],for downsample path,the distance between points when generating a path
  inflation_distance: 0.6           # [m] [default = robot_radius + 0.05]

gsl_smooth:
  step_points: 10