controller_costmap:
    global_frame: map
    robot_base_frame: base_link
    update_frequency: 10.0
    publish_frequency: 2.5

    width: 8
    height: 8
    resolution: 0.05
     
    transform_tolerance: 0.5
    rolling_window: true
    always_send_full_costmap: true
    footprint: [[0.6, 0.4], [-0.6, 0.4], [-0.6,-0.4],[0.6,-0.4]]

    plugins:
            #- {name: ogm_layer, type: "local_ogm_voxel_layer/LocalOgmVoxelLayer"}
      - {name: obstacle_layer,          type: "navit_costmap::ObstacleLayer"}
      - {name: inflation_layer,          type: "navit_costmap::InflationLayer"}

    obstacle_layer:
        observation_sources: lidar_1
        lidar_1:
            topic: scan
            sensor_frame: laser_link
            data_type: LaserScan
            marking: true
            clearing: true
            obstacle_range: 8
        lidar_2:
            topic: scan_filtered_2
            sensor_frame: laser_link
            data_type: LaserScan
            marking: true
            clearing: true
            obstacle_range: 8
    inflation_layer:
        inflation_radius: 0.1
        cost_scaling_factor: 0.5

    ogm_layer:
        plugin: "local_ogm_voxel_layer/LocalOgmVoxelLayer"
        enabled: True
        voxel_decay: 15.
        decay_model: 0
        voxel_size: 0.05
        track_unknown_space: True
        max_obstacle_height: 100.0
        unknown_threshold: 1
        mark_threshold: 0
        update_footprint_enabled: True
        combination_method: 1
        origin_z: 10.0
        publish_voxel_map: True
        transform_tolerance: 0.2
        mapping_mode: False
        map_save_duration: 60.0
        observation_sources: pointcloud localogm
        pointcloud:
            data_type: PointCloud2
            topic: /costmap_node/local_perception/point_cloud_image_all2
            marking: True
            clearing: True
            obstacle_range: 300.0
            min_obstacle_height: 0.08
            max_obstacle_height: 100.0
            expected_update_rate: 0.0
            observation_persistence: 0.0
            inf_is_valid: False
            voxel_filter: False
            clear_after_reading: True
            max_z: 10.0
            min_z: 10.0
            vertical_fov_angle: 3.8745
            horizontal_fov_angle: 3.048
            decay_acceleration: 15.0
            model_type: 0
        localogm:
            data_type: MAP
            marking: True
            clearing: True
            obstacle_range: 300.0
            min_obstacle_height: 0.08
            max_obstacle_height: 100.0
            expected_update_rate: 0.0
            observation_persistence: 0.0
            inf_is_valid: False
            voxel_filter: False
            clear_after_reading: True
            max_z: 10.0
            min_z: 10.0
            vertical_fov_angle: 0    
