nav_controller:
    - {name: tracking, type: teb_local_planner/TebLocalPlannerROS}
    - {name: avoidance, type: teb_local_planner/TebLocalPlannerROS}
control_wait_timeout: 0.5
# should be tuned for tracking only
tracking:
  odom_topic: odom

  # Trajectory

  teb_autosize: True
  dt_ref: 0.3
  dt_hysteresis: 0.1
  max_samples: 500
  global_plan_overwrite_orientation: True
  allow_init_with_backwards_motion: False
  max_global_plan_lookahead_dist: 3.0
  global_plan_viapoint_sep: 0.3
  global_plan_prune_distance: 0.3
  exact_arc_length: False
  feasibility_check_no_poses: 5
  publish_feedback: False

  # Robot
  max_vel_x: 0.2
  max_vel_x_backwards: 0.2
  max_vel_y: 0.0
  max_vel_theta: 0.5 #0.3
  acc_lim_x: 0.5
  acc_lim_theta: 0.2
  min_turning_radius: 0.0 # diff-drive robot (can turn on place!)

  footprint_model:
    type: "point"

  # GoalTolerance

  xy_goal_tolerance: 0.15
  yaw_goal_tolerance: 0.1
  free_goal_vel: True
  complete_global_plan: True

  # Obstacles

  min_obstacle_dist: 0.25 # This value must also include our robot radius, since footprint_model is set to "point".
  inflation_dist: 0.6
  include_costmap_obstacles: True
  costmap_obstacles_behind_robot_dist: 1.5
  obstacle_poses_affected: 15

  dynamic_obstacle_inflation_dist: 0.6
  include_dynamic_obstacles: False

  # Optimization
  no_inner_iterations: 5
  no_outer_iterations: 4
  optimization_activate: True
  optimization_verbose: False
  penalty_epsilon: 0.1
  obstacle_cost_exponent: 4
  weight_max_vel_x: 2
  weight_max_vel_theta: 1
  weight_acc_lim_x: 1
  weight_acc_lim_theta: 2
  weight_kinematics_nh: 1000
  weight_kinematics_forward_drive: 1000
  weight_kinematics_turning_radius: 1
  weight_optimaltime: 10 # must be > 0
  weight_shortest_path: 0
  weight_obstacle: 1
  weight_inflation: 0.2
  weight_dynamic_obstacle: 0
  weight_dynamic_obstacle_inflation: 0
  weight_viapoint: 100
  weight_adapt_factor: 2

  # Homotopy Class Planner
  enable_homotopy_class_planning: False

#  Recovery
  shrink_horizon_backup: True
  shrink_horizon_min_duration: 10
  oscillation_recovery: True
  oscillation_v_eps: 0.1
  oscillation_omega_eps: 0.1
  oscillation_recovery_min_duration: 10
  oscillation_filter_duration: 10

  # should be tuned for avoidance only
avoidance:
  odom_topic: odom

  # Trajectory

  teb_autosize: True
  dt_ref: 0.2
  dt_hysteresis: 0.1
  max_samples: 500
  global_plan_overwrite_orientation: True
  allow_init_with_backwards_motion: False
  max_global_plan_lookahead_dist: 3.0
  global_plan_viapoint_sep: 0.1
  global_plan_prune_distance: 0.3
  exact_arc_length: False
  force_reinit_new_goal_dist: 1.0
  force_reinit_new_goal_angular: 0.78
  feasibility_check_no_poses: 2
  publish_feedback: False

  # Robot
  max_vel_x: 0.2
  max_vel_x_backwards: 0.2
  max_vel_y: 0.0
  max_vel_theta: 0.3
  acc_lim_x: 0.5
  acc_lim_theta: 0.5
  min_turning_radius: 0.0 # diff-drive robot (can turn on place!)

  footprint_model:
    # type: "circular"
    radius: 0.5
    type: "point"

  # GoalTolerance

  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.05
  free_goal_vel: True
  complete_global_plan: True

  # Obstacles

  min_obstacle_dist: 0.55 # This value must also include our robot radius, since footprint_model is set to "point".
  inflation_dist: 0.8
  include_costmap_obstacles: True
  costmap_obstacles_behind_robot_dist: 1.5
  obstacle_poses_affected: 15

  dynamic_obstacle_inflation_dist: 0.6
  include_dynamic_obstacles: False

  # Optimization
  no_inner_iterations: 5
  no_outer_iterations: 4
  optimization_activate: True
  optimization_verbose: False
  penalty_epsilon: 0.1
  weight_max_vel_x: 2
  weight_max_vel_theta: 1
  weight_acc_lim_x: 1
  weight_acc_lim_theta: 1
  weight_kinematics_nh: 1000
  weight_kinematics_forward_drive: 1000
  weight_kinematics_turning_radius: 1
  weight_optimaltime: 10 # must be > 0
  weight_shortest_path: 0
  weight_obstacle: 640
  weight_inflation: 0.2
  weight_dynamic_obstacle: 0
  weight_dynamic_obstacle_inflation: 0
  weight_viapoint: 10
  weight_adapt_factor: 2
  obstacle_cost_exponent: 3.0

  # Homotopy Class Planner
  enable_homotopy_class_planning: False

#  Recovery
  shrink_horizon_backup: True
  shrink_horizon_min_duration: 10
  oscillation_recovery: True
  oscillation_v_eps: 0.1
  oscillation_omega_eps: 0.1
  oscillation_recovery_min_duration: 10
  oscillation_filter_duration: 10
