controller_costmap:
    global_frame: odom
    robot_base_frame: base_link
    update_frequency: 5.0
    publish_frequency: 2.5

    width: 10
    height: 10
    resolution: 0.05
     
    transform_tolerance: 0.5
    rolling_window: true
    always_send_full_costmap: true

    plugins:
      - {name: obstacle_layer,          type: "navit_costmap::VoxelLayer"}
      - {name: inflation_layer,         type: "navit_costmap::InflationLayer"}    

    obstacle_layer:
        observation_sources: lidar
        lidar:
            topic: hokuyo_lida/scan
            sensor_frame: laser_link
            data_type: LaserScan
            marking: true
            clearing: true
            obstacle_range: 8
            raytrace_range: 20

    inflation_layer:
        inflation_radius: 0.0
        cost_scaling_factor: 1.0


