controller_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.5
  footprint: [[0.5,0.3],[-0.5,0.3],[-0.5,-0.3],[0.5,-0.3]]
  # footprint: [[0.1,0.1],[-0.1,0.1],[-0.1,-0.1],[0.1,-0.1]]

  width: 5
  height: 5
  resolution: 0.05

  transform_tolerance: 0.5
  rolling_window: true
  always_send_full_costmap: true

  plugins:
    #- {name: static_layer,            type: "navit_costmap::StaticLayer"}
    - {name: obstacle_layer,          type: "navit_costmap::VoxelLayer"}
    - {name: inflation_layer,         type: "navit_costmap::InflationLayer"}


  obstacle_layer:
    observation_sources: lidar
    lidar:
      topic: scan
      sensor_frame: base_link
      data_type: LaserScan
      marking: true
      clearing: true
      obstacle_range: 8
      raytrace_range: 20

  inflation_layer:
    inflation_radius: 0.2
    cost_scaling_factor: 1.5




nav_controller:
  - name: test_1
    type: base_local_planner/TrajectoryPlannerROS

  - name: test_2
    type: base_local_planner/TrajectoryPlannerROS

  - name: test_3
    type: teb_local_planner/TebLocalPlannerROS

