# BackToReferenceLine.action
nav_msgs/Path reference_line        #参考线轨迹
string bt_name                      #行为树名
---
int16 error_code                    #错误码
string error_msg                    #错误信息
---
int16 num_of_revoveries             #重试次数
float32 distance_remaining          #剩余距离
std_msgs/Duration time_elapsed      #已用时间
std_msgs/Duration time_remaining    #剩余时间
