# MoveThroughPoses.action
uint64[] poses #路点编号
string bt_name #行为树名 optional, 含有默认行为树
---
int16 error_code #错误码
string error_msg #错误信息
---
uint64 current_pose
int16 num_of_poses_remaining
int16 num_of_revoveries #重试次数
float32 distance_remaining  #剩余距离
std_msgs/Duration time_elapsed   #已用时间
std_msgs/Duration time_remaining  #剩余时间
