define dock model
(
    block
      (
            points 6
            point[0] [0.75 0]
            point[1] [1 0.25]
            point[2] [1 0.75]
            point[3] [0.75 1]
            point[4] [0 1]
            point[5] [0 0]
            z [0 1]
      )
      
)

define obs model
(
  block
  (
    points 4
    point[0] [3 0]
    point[1] [3 3]
    point[2] [0 3]
    point[3] [0 0]
    z [0 1]
  )
  laser_return 1
)

define obs0 model
(
  block
  (
    points 4
    point[0] [3 0]
    point[1] [3 3]
    point[2] [0 3]
    point[3] [0 0]
    z [0 1]
  )
  laser_return 1
)

define obs1 model
(
  block
  (
    points 4
    point[0] [3 0]
    point[1] [3 3]
    point[2] [0 3]
    point[3] [0 0]
    z [0 1]
  )
  laser_return 1
)

define obs2 model
(
  block
  (
    points 4
    point[0] [3 0]
    point[1] [3 3]
    point[2] [0 3]
    point[3] [0 0]
    z [0 1]
  )
  laser_return 1
)
