test_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 1
  publish_frequency: 5
  track_unknown_space: true
  width: 10
  height: 10
  resolution: 0.05
  # rolling_window: true
  always_send_full_costmap: true

  plugins:
    - {name: static_layer,            type: "costmap_2d::StaticLayer"}
    - {name: voronoifield_layer,      type: "costmap_2d::VoronoiFieldLayer"}
    # - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}

  voronoifield_layer:
    enabled:              true
    alpha:                1.0
    dist2O:               5.0

  inflation_layer:
    enabled:              true
    cost_scaling_factor:  0.5  # exponential rate at which the obstacle cost drops off (default: 10)
    inflation_radius:     2.5  # max. distance from an obstacle at which costs are incurred for planning paths.

  static_layer:
    enabled:              true
    map_topic:            "/map"
